### ISSUE TITLE
亲，你有sonarqube v7.2.1吗？

### ISSUE THREAD

**Issue by wujiegoodluck** [sch1111878/sonar-objc-plugins#1]
可否上传一下sonarqube v7.2.1，万分感谢，期待回复

**Comment by JxJPu9bD** [comment]
官网就有的 https://www.sonarqube.org/downloads/
![image](https://user-images.githubusercontent.com/12554248/68640048-8627f480-0541-11ea-8d06-78bf284830d2.png)
